/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import JpaControllers.EtudiantJpaController;
import JpaControllers.GroupeJpaController;
import entities.Etudiant;
import static entities.Etudiant_.groupe;
import entities.Groupe;
import java.awt.Frame;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tchokouani
 */
public class JD_CreateEtudiant extends javax.swing.JDialog {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("StudentGrouperPU");
    EtudiantJpaController etudianJpaController = new EtudiantJpaController(emf);
    GroupeJpaController groupeJpaController = new GroupeJpaController(emf);

    /**
     * Creates new form JD_Etudiants
     */
    public JD_CreateEtudiant(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        List<Groupe> groupes = groupeJpaController.findGroupeEntities();
        jComboBox_Groupes.setModel(new DefaultComboBoxModel(groupes.toArray()));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Nom = new javax.swing.JLabel();
        jLabel_Prenom = new javax.swing.JLabel();
        jComboBox_Sexes = new javax.swing.JComboBox();
        jLabel_Sexe = new javax.swing.JLabel();
        jLabel_Groupes = new javax.swing.JLabel();
        jTextField_Nom = new javax.swing.JTextField();
        jTextField_Prenom = new javax.swing.JTextField();
        jComboBox_Groupes = new javax.swing.JComboBox();
        jButton_Valider = new javax.swing.JButton();
        jButton_Annuler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();
        jLabel_Groupes1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajout d'un etudiants");

        jLabel_Nom.setText("Nom :");

        jLabel_Prenom.setText("Prenom : ");

        jComboBox_Sexes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme" }));

        jLabel_Sexe.setText("Sexe");

        jLabel_Groupes.setText("Groupes :");

        jComboBox_Groupes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBox_Groupes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_GroupesItemStateChanged(evt);
            }
        });
        jComboBox_Groupes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_GroupesActionPerformed(evt);
            }
        });

        jButton_Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/16x16/accept.png"))); // NOI18N
        jButton_Valider.setText("Valider");
        jButton_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ValiderActionPerformed(evt);
            }
        });

        jButton_Annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/annuler.gif"))); // NOI18N
        jButton_Annuler.setText("Annuler");
        jButton_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnnulerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("aakar", 1, 18)); // NOI18N
        jLabel1.setText("Insertion");

        try {
            dateChooserCombo1.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2017, 0, 1),
                new java.util.GregorianCalendar(2017, 0, 1))));
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }

    jLabel_Groupes1.setText("Date de naiss :");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(jButton_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)
                    .addComponent(jButton_Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel_Groupes1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel_Prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_Groupes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_Sexe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_Nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(59, 59, 59)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Prenom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                                    .addComponent(jComboBox_Sexes, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_Groupes, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_Nom)))
                            .addGap(0, 0, Short.MAX_VALUE)))))
            .addContainerGap())
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel_Groupes, jLabel_Sexe});

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_Annuler, jButton_Valider});

    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(27, 27, 27)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_Sexe)
                .addComponent(jComboBox_Sexes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_Groupes, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jComboBox_Groupes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(dateChooserCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_Groupes1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButton_Annuler, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jButton_Valider, javax.swing.GroupLayout.Alignment.TRAILING))
            .addGap(33, 33, 33))
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel_Groupes, jLabel_Nom, jLabel_Prenom, jLabel_Sexe});

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_Annuler, jButton_Valider});

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_GroupesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_GroupesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_GroupesActionPerformed

    private void jButton_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ValiderActionPerformed
        // TODO add your handling code here:

        Etudiant etudiant = new Etudiant();
        etudiant.setNom(jTextField_Nom.getText());
        etudiant.setPrenom(jTextField_Prenom.getText());
        etudiant.setGroupe((Groupe) jComboBox_Groupes.getSelectedItem());
        Calendar dateNaiss = dateChooserCombo1.getSelectedDate();
        etudiant.setDateNaiss(dateNaiss.getTime());
        //setSexe
        int choix = jComboBox_Sexes.getSelectedIndex();
        if (choix == -1) {
        } else{
            if (choix == 0) {
                etudiant.setSexe("H");
            }else{
                etudiant.setSexe("F");
            }
        }
        try {
            etudianJpaController.create(etudiant);
            JOptionPane.showMessageDialog(this, "etudiant enregistré avec succes", "info", 1);
        } catch (Exception ex) {
            System.out.println("erreur d'enreg de l'etudiant "+etudiant.getNom());
            Logger.getLogger(JD_CreateEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        //jpe.refreshEtudiants();
        
        dispose();
    }//GEN-LAST:event_jButton_ValiderActionPerformed

    private void jButton_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnnulerActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_AnnulerActionPerformed

    private void jComboBox_GroupesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_GroupesItemStateChanged
        // TODO add your handling code here:
        System.out.println("change");
    }//GEN-LAST:event_jComboBox_GroupesItemStateChanged

    /**
     * @para**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************m
     * args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JD_CreateEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JD_CreateEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JD_CreateEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JD_CreateEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JD_CreateEtudiant dialog = new JD_CreateEtudiant(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButton_Annuler;
    private javax.swing.JButton jButton_Valider;
    private javax.swing.JComboBox jComboBox_Groupes;
    private javax.swing.JComboBox jComboBox_Sexes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Groupes;
    private javax.swing.JLabel jLabel_Groupes1;
    private javax.swing.JLabel jLabel_Nom;
    private javax.swing.JLabel jLabel_Prenom;
    private javax.swing.JLabel jLabel_Sexe;
    private javax.swing.JTextField jTextField_Nom;
    private javax.swing.JTextField jTextField_Prenom;
    // End of variables declaration//GEN-END:variables
}
