/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Controllers.exceptions.NonexistentEntityException;
import JpaControllers.EtudiantJpaController;
import JpaControllers.GroupeJpaController;
import entities.Etudiant;
import static entities.Etudiant_.groupe;
import entities.Groupe;
import java.awt.Frame;
import java.sql.Date;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tchokouani
 */
public class JD_UpdateEtudiant extends javax.swing.JDialog {

    EntityManagerFactory emf = Persistence.createEntityManagerFactory("StudentGrouperPU");
    EtudiantJpaController etudianJpaController = new EtudiantJpaController(emf);
    GroupeJpaController groupeJpaController = new GroupeJpaController(emf);
    
    Etudiant etudiant = new Etudiant();

    /**
     * Creates new form JD_Etudiants
     */
    public JD_UpdateEtudiant(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        List<Groupe> groupes = groupeJpaController.findGroupeEntities();
        jComboBox_Groupes.setModel(new DefaultComboBoxModel(groupes.toArray()));
    }

    public JD_UpdateEtudiant(java.awt.Frame parent, boolean modal, Etudiant etudiant) {
        super(parent, modal);
        initComponents();
        jTextField_Nom.setText(etudiant.getNom());
                jTextField_Prenom.setText(etudiant.getPrenom());
        jTextField_Nom.setText(etudiant.getNom());
        
        // chargement de la comboBox_groupes
        List<Groupe> groupes = groupeJpaController.findGroupeEntities();
        jComboBox_Groupes.setModel(new DefaultComboBoxModel(groupes.toArray()));
        
        this.etudiant = etudiant;
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Nom = new javax.swing.JLabel();
        jLabel_Prenom = new javax.swing.JLabel();
        jComboBox_Sexes = new javax.swing.JComboBox();
        jLabel_Sexe = new javax.swing.JLabel();
        jLabel_Groupes = new javax.swing.JLabel();
        jTextField_Nom = new javax.swing.JTextField();
        jTextField_Prenom = new javax.swing.JTextField();
        jComboBox_Groupes = new javax.swing.JComboBox();
        jButton_Valider = new javax.swing.JButton();
        jButton_Annuler = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonDeleteEtudiant = new javax.swing.JButton();
        jLabel_Groupes1 = new javax.swing.JLabel();
        dateChooserCombo1 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifier un etudiants");

        jLabel_Nom.setText("Nom :");

        jLabel_Prenom.setText("Prenom : ");

        jComboBox_Sexes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Homme", "Femme" }));
        jComboBox_Sexes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_SexesItemStateChanged(evt);
            }
        });

        jLabel_Sexe.setText("Sexe");

        jLabel_Groupes.setText("Groupes :");

        jComboBox_Groupes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));
        jComboBox_Groupes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_GroupessActionPerformed(evt);
            }
        });

        jButton_Valider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/16x16/accept.png"))); // NOI18N
        jButton_Valider.setText("Valider");
        jButton_Valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ValiderActionPerformed(evt);
            }
        });

        jButton_Annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/annuler.gif"))); // NOI18N
        jButton_Annuler.setText("Annuler");
        jButton_Annuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnnulerActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("aakar", 1, 18)); // NOI18N
        jLabel1.setText("Modification");

        jButtonDeleteEtudiant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/16x16/delete.png"))); // NOI18N
        jButtonDeleteEtudiant.setText("Supprimer");
        jButtonDeleteEtudiant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteEtudiantActionPerformed(evt);
            }
        });

        jLabel_Groupes1.setText("Date de naiss :");

        try {
            dateChooserCombo1.setDefaultPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2017, 0, 1),
                new java.util.GregorianCalendar(2017, 0, 1))));
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jButton_Annuler, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton_Valider, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel_Prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Groupes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Groupes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Sexe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(25, 25, 25)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextField_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_Sexes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox_Groupes, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateChooserCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addComponent(jButtonDeleteEtudiant))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton_Annuler, jButton_Valider});

    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel_Nom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jTextField_Prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel_Prenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBox_Sexes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel_Sexe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jComboBox_Groupes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel_Groupes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(dateChooserCombo1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addComponent(jLabel_Groupes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_Annuler)
                .addComponent(jButton_Valider))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButtonDeleteEtudiant)
            .addGap(26, 26, 26))
    );

    layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton_Annuler, jButton_Valider});

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_GroupessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_GroupessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_GroupessActionPerformed

    private void jButton_ValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ValiderActionPerformed
        etudiant.setNom(jTextField_Nom.getText());
        etudiant.setPrenom(jTextField_Prenom.getText());
        etudiant.setGroupe((Groupe) jComboBox_Groupes.getSelectedItem());
        Calendar dateNaiss = dateChooserCombo1.getSelectedDate();
        etudiant.setDateNaiss(dateNaiss.getTime());
        //setSexe
        int choix = jComboBox_Sexes.getSelectedIndex();
        if (choix == -1) {
        } else{
            if (choix == 1) {
                            etudiant.setSexe("H");
            }else{
                            etudiant.setSexe("F");
            }
        }
        try {
            etudianJpaController.edit(etudiant);
                    JOptionPane.showMessageDialog(this, "Etudiant modifié avec succes", "info", 1);
                                    System.out.println("modification effectue sur"+ etudiant);

        } catch (Exception ex) {
                System.out.println("erreur de modification");
            Logger.getLogger(JD_UpdateEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        //jpe.refreshEtudiants();
        dispose();
    }//GEN-LAST:event_jButton_ValiderActionPerformed

    private void jButton_AnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnnulerActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton_AnnulerActionPerformed

    private void jComboBox_SexesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_SexesItemStateChanged
        int choix = jComboBox_Sexes.getSelectedIndex();
        if (choix == -1) {
        } else{
            if (choix == 0) {
                etudiant.setSexe("H");
            }else{
                etudiant.setSexe("F");
            }
        }
    }//GEN-LAST:event_jComboBox_SexesItemStateChanged

    private void jButtonDeleteEtudiantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteEtudiantActionPerformed
        try {
            etudianJpaController.destroy(etudiant.getId());
            System.out.println("etudiant supprime");
        } catch (NonexistentEntityException ex) {
            System.out.println("Erreur de suppression");
            Logger.getLogger(JD_UpdateEtudiant.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jButtonDeleteEtudiantActionPerformed

    /**
     * @para**********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************m
     * args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JD_UpdateEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JD_UpdateEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JD_UpdateEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JD_UpdateEtudiant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JD_UpdateEtudiant dialog = new JD_UpdateEtudiant(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo1;
    private javax.swing.JButton jButtonDeleteEtudiant;
    private javax.swing.JButton jButton_Annuler;
    private javax.swing.JButton jButton_Valider;
    private javax.swing.JComboBox jComboBox_Groupes;
    private javax.swing.JComboBox jComboBox_Sexes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Groupes;
    private javax.swing.JLabel jLabel_Groupes1;
    private javax.swing.JLabel jLabel_Nom;
    private javax.swing.JLabel jLabel_Prenom;
    private javax.swing.JLabel jLabel_Sexe;
    private javax.swing.JTextField jTextField_Nom;
    private javax.swing.JTextField jTextField_Prenom;
    // End of variables declaration//GEN-END:variables
}
